# Workflow for deploying static content to GitHub pages
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

  # Allows to run this workflow manually from the "Actions" tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ "en", "uk" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry

      - name: Install dependencies
        run: poetry install --with docs

      - name: Build documents
        run: |
          poetry run sphinx-build -b html -D language=${{ matrix.language }} docs _build/${{ matrix.language }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }}
          path: _build/${{ matrix.language }}

  merge:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: pages-content
          separate-directories: true
          delete-merged: true

  deploy:
    runs-on: ubuntu-latest
    needs:
      - merge
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-content
          path: ./_site

      - name: Set up Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
